"""gis id not unique

Revision ID: 002a8c27698a
Revises: ce4d4c5b1fff
Create Date: 2025-02-10 22:43:23.320129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002a8c27698a'
down_revision: Union[str, None] = 'ce4d4c5b1fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_places_gis_id', table_name='places')
    op.create_index(op.f('ix_places_gis_id'), 'places', ['gis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_gis_id'), table_name='places')
    op.create_index('ix_places_gis_id', 'places', ['gis_id'], unique=1)
    # ### end Alembic commands ###
